apiVersion: apps/v1
kind: Deployment
metadata:
  name: trabalho-infnet
  namespace: gitops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trabalho-infnet
  template:
    metadata:
      labels:
        app: trabalho-infnet
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
